@Nirvana.Data.Web_HostAddress = http://localhost:5287

GET {{Nirvana.Data.Web_HostAddress}}/health
Accept: application/json

###

GET {{Nirvana.Data.Web_HostAddress}}/weatherforecast/
Accept: application/json

###
